LOG_ON = False
LOG_SENSORS_ON = False
LOG_SM_ON = True
LOG_DB_ON = True
LOG_TASK_INFO_ON = False
LOG_INPUT_PARAM_ON = False
LOG_CALL_SEQUENCE = False

TURN_OFF_POWER_SUPPLY = False
TURN_ON_POWER_SUPPLY = True

START_CALIBRATE = True
STOP_CALIBRATE = False

TURN_OFF = 0
TURN_ON = 1
COMPLETED = True
MEASUREMENT_FREE = 3
MEASUREMENT_START = 4
MEASUREMENT_ONGOING = 5
MEASUREMENT_HOLD = 6
MEASUREMENT_STOP = 7

# STEP FOR STATE MACHINE
STEP_IDLE = 0
STEP_TURN_POWER_ON = 1
STEP_TURN_POWER_OFF = 2
STEP_MEASUREMENT = 3
STEP_CALIBRATION = 4

SCANNING_RESULT = list()

