LOG_ON = True

TURN_OFF_POWER_SUPPLY = False
TURN_ON_POWER_SUPPLY = True

TURN_OFF = 0
TURN_ON = 1
COMPLETED = True
MEASUREMENT_FREE = 3
MEASUREMENT_START = 4
MEASUREMENT_ONGOING = 5
MEASUREMENT_HOLD = 6
MEASUREMENT_STOP = 7

SCANNING_RESULT = list()

